services:
  - type: web
    name: scenesound-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd python_service && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: "*" 